locale: "nl-NL"

theme: # NONE - DEFAULT IS

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .idea/
  - .git*
  - .editorconfig
  - _config
  - Gemfile
  - Gemfile.lock
  - README.md
